column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 3
quote_style = "AutoPreferSingle"
call_parentheses = "Input"
collapse_simple_statement = "Never"

[sort_requires]
enabled = true
